title: G P Mohith Chowdary
logo: /assets/img/logo.png

description: I am a '22 Graduate from BITS Pilani K K Birla Goa Campus, looking for oppurtunities in the Data Science & Web Development domains.

theme: jekyll-theme-minimal


